name: mysql_protocol
description: MySQL protocol for Dart.
version: 0.0.1
homepage: https://github.com/unicorn-dart/mysql_protocol

environment:
  sdk: ">=2.18.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  build: ^2.3.1
  equatable: ^2.0.5
  source_gen: ^1.2.6
  version: ^3.0.2
